fn main() -> void {
    match x {
        DivisionError { message } => print.info("Error"),
    }
}
